### ISSUE TITLE
Data Science Track Courses to be Completed

### ISSUE THREAD

**Issue by mikejloria** [mikejloria/TreehouseCourses#2]
## TODO

*Courses left to complete the Treehouse Data Science Track*

* [ ] Object Oriented Python
* [ ] SQL
* [ ] Data Visualization with Matplotlib
* [ ] Numpy
* [ ] Pandas
* [ ] Cleaning and Preparing Data
* [ ] Data Visualization with Matplotlib
* [ ] Scraping Data from the Web
* [ ] Big Data
* [ ] Machine Learning

💯 ☕️  ⚡️
