### ISSUE TITLE
Full Stack Javascript

### ISSUE THREAD

**Issue by mikejloria** [mikejloria/TreehouseCourses#7]
## TODO

*Courses in the Treehouse Full Stack Javascript Track*

* [ ] Introducing JavaScript
* [ ] Javascript Basics
* [ ] JavaScript Loops, Arrays and Objects
* [ ] The Landscape of JavaScript
* [ ] Getting Started With ES2015
* [ ] JavaScript and the DOM
* [ ] jQuery Basics
* [ ] Ajax Basics
* [ ] Asynchronus Programming with JavaScript
* [ ] Working with the Fetch API
* [ ] Object Oriented JavaScript
* [ ] Object Oriented JavaScript: Challenge
* [ ] Learn More About ES2015
* [ ] Node.js Basics
* [ ] Exploring JavaScript Conditionals
* [ ] Build a Simple Dynamic Site with Node.js
* [ ] npm Basics
* [ ] Using npm as a Task Runner
* [ ] Express Basics
* [ ] Understanding Closures in JavaScript
* [ ] Debug Node Applications with Visual Studio Code
* [ ] Asynchronus Code in Express
* [ ] REST APIs with Express
* [ ] SQL Basics
* [ ] Modifying Data with SQL
* [ ] Using SQL ORMs with Node.js
* [ ] Using Sequelize ORM with Express

💯 ☕️  ⚡️
